do $$ begin create role anon; exception when others then null; end $$;
do $$ begin create role authenticated; exception when others then null; end $$;
create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('test.uid', true), '')::uuid $$;
grant usage on schema auth to authenticated;
create table profiles (id uuid primary key, name text, role text);
insert into profiles values ('00000000-0000-0000-0000-00000000000a','Maria Oliveira','admin'),('00000000-0000-0000-0000-00000000000b','Tarefeira','tarefeiro');
create function current_app_role() returns text language sql stable security definer set search_path=public as $$ select role from profiles where id = auth.uid() $$;
create table app_data (key text primary key, value json);
alter table app_data enable row level security;
create policy app_data_select on app_data for select to authenticated using (true);
create policy app_data_admin_all on app_data for all to authenticated using (current_app_role()='admin') with check (current_app_role()='admin');
create policy app_data_tarefeiro_update on app_data for update to authenticated using (current_app_role()='tarefeiro' and key='chbv_terceiros') with check (current_app_role()='tarefeiro' and key='chbv_terceiros');
create policy app_data_tarefeiro_insert on app_data for insert to authenticated with check (current_app_role()='tarefeiro' and key='chbv_terceiros');
create table app_data_history (id serial primary key, saved_at timestamptz default now(), doctors json, schedules json, terceiros json, rotations json);
alter table app_data_history enable row level security;
create policy "Authenticated users can read history" on app_data_history for select to authenticated using (true);
grant select, insert, update, delete on app_data, app_data_history, profiles to authenticated;
grant usage on all sequences in schema public to authenticated;
alter default privileges in schema public grant all on tables to anon, authenticated; alter default privileges in schema public grant all on sequences to anon, authenticated;
